# Generated by Django 2.0.5 on 2018-05-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanel', models.CharField(blank=True, default='', max_length=100)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Record')),
            ],
        ),
    ]
